FROM node:22-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ARG WORDPRESS_GRAPHQL_ENDPOINT
ARG WORDPRESS_REVALIDATE_SECRET
ARG CONTACT_WEBHOOK_URL

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV WORDPRESS_GRAPHQL_ENDPOINT=$WORDPRESS_GRAPHQL_ENDPOINT
ENV WORDPRESS_REVALIDATE_SECRET=$WORDPRESS_REVALIDATE_SECRET
ENV CONTACT_WEBHOOK_URL=$CONTACT_WEBHOOK_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
